# Generated by Django 6.0.3 on 2026-04-04 15:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, help_text='External ID from TheMovieDB', null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('popular_movies', 'Popular Movies'), ('top_rated_movies', 'Top Rated Movies'), ('upcoming_movies', 'Upcoming Movies')], db_index=True, max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='started', max_length=20)),
                ('movies_fetched', models.PositiveIntegerField(default=0)),
                ('movies_created', models.PositiveIntegerField(default=0)),
                ('movies_updated', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list, help_text='List of errors encountered during ingestion')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the ingestion job')),
            ],
            options={
                'verbose_name': 'Ingestion Log',
                'verbose_name_plural': 'Ingestion Logs',
                'db_table': 'ingestion_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_type', '-started_at'], name='ing_job_started_idx'), models.Index(fields=['status', '-started_at'], name='ing_status_started_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, help_text='External ID from TheMovieDB', null=True, unique=True)),
                ('source', models.CharField(choices=[('external', 'External (TMDB)'), ('internal', 'Internal (User Created)')], db_index=True, default='internal', max_length=20)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, help_text='Runtime in minutes', null=True)),
                ('popularity', models.DecimalField(blank=True, db_index=True, decimal_places=4, help_text='Popularity score', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('vote_average', models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))])),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('poster_path', models.URLField(blank=True)),
                ('backdrop_path', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rumored', 'Rumored'), ('planned', 'Planned'), ('in_production', 'In Production'), ('post_production', 'Post Production'), ('released', 'Released'), ('canceled', 'Canceled')], db_index=True, default='released', max_length=20)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('synced_to_mongo_at', models.DateTimeField(blank=True, help_text='Timestamp of last sync to MongoDB', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movies',
                'ordering': ['-popularity', '-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))])),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_active', '-popularity'], name='movies_active_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-release_date', '-popularity'], name='movies_date_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['source', '-created_at'], name='movies_source_created_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['status', '-release_date'], name='movies_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='movies_search_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['movie', '-created_at'], name='reviews_movie_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='unique_movie_user_review'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('movie', 'user')},
        ),
    ]
